--liquibase formatted sql

--changeset kashapov-as:20231025-1 failOnError:true
--comment: create users table.
--preconditions onFail:mark_ran onError:halt
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'users';
create table if not exists users (
                                     id bigint generated by default as identity primary key,
                                     first_name varchar(255) not null,
    last_name varchar(255) not null,
    login varchar(255) not null unique,
    password varchar(255) not null,
    phone varchar(255),
    role varchar(255) not null,
    date_of_created timestamp
    );

--changeset kashapov-as:20231025-2 failOnError:true
--comment: create category table.
--preconditions onFail:mark_ran onError:halt
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'category';
create table if not exists category (
                                        id bigint generated by default as identity primary key,
                                        category_title varchar(255) not null unique,
    user_id bigint not null,
    constraint fk_category_users foreign key (user_id) references users(id)
    );

--changeset kashapov-as:20231025-3 failOnError:true
--comment: create task table.
--preconditions onFail:mark_ran onError:halt
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'task';
create table if not exists tasks (
                                     id bigint generated by default as identity primary key,
                                     task_title varchar(255),
    created_task timestamp,
    title varchar(50),
    status varchar(50),
    category_id bigint,
    user_id bigint not null,
    constraint fk_task_category foreign key (category_id) references category(id),
    constraint fk_task_users foreign key (user_id) references users(id)
    );